### PR TITLE
Reinstate mixlib install platform mapping logic

### LINKED ISSUE #168: SLES: Chef-server no longer installs with version 2.1.0
### Cookbook version
2.1.0

### Chef-client version
12.19.36

### Platform Details
AME="SLES"
VERSION="12-SP2"
VERSION_ID="12.2"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP2"
ID="sles"

### Scenario:
Install chef-server using chef-ingredient wrapper on Suse.
This was working last night with ingredients version 2.0.5

### Steps to Reproduce:
take dependency of latest chef-ingredient cookbook: 2.1.0
define the following resource:

```
chef_server node['chef_server']['fqdn'] do
  version :latest
  config <<-EOS
api_fqdn '#{node['chef_server']['fqdn']}'
oc_id['applications'] = {
  "supermarket"=>{"redirect_uri"=>"https://supermarket.services.com/auth/chef_oauth2/callback"}
}
postgresql['username'] = 'chefpsql'
postgresql['db_superuser'] = 'chefpsql'
EOS
  platform 'el'
  platform_version '6'
  addons manage: { version: '2.4.3', config: '', platform: 'el', platform_version: '6' },
         :"push-jobs-server" => { version: '2.1.0', config: '', platform: 'el', platform_version: '6' }
  accept_license true
  #data_collector_url 'https://automate.services.com/data-collector/v0/' if search(:node, 'name:automate-centos-68', filter_result: { 'name' => ['name'] }) # ~FC003
end
```

### Expected Result:
success

### Actual Result:
https://gist.github.com/vinyar/3e4bdaa8ce0ee7850ebb473fcbbca887

### PR DESCRIPTION
**Pull request by wrightp**
- Remove logic ported from omnibus
- Remove default values from platform-related properties
- Reinstate Mixlib Install platform detection
- Never modify platform-related properties when explicity set
- Auto-detect and set platform-related properties when not explicity set

Signed-off-by: Patrick Wright <patrick@chef.io>

### Description

[Describe what this change achieves]

### Issues Resolved

#168

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by wrightp** [comment]
@vinyar FYI

File: libraries/helpers.rb [hunk 1]
```diff
@@ -270,27 +270,49 @@ def installer
...
-        options.merge!(platform_details)
+    def resolve_platform!
+      # Auto detect platform
+      detected_platform = Mixlib::Install.detect_platform
 
-        Mixlib::Install.new(options)
+      if new_resource.platform.nil?
+        # set detected suse platforms to sles for artifact discovery
+        if detected_platform[:platform] =~ /suse/
+          new_resource.platform('sles')
```
Comment (schisamo) [inline libraries/helpers.rb]: We should remove this for now as it won't do the right thing in 80% of our products (the ones that don't have native `sles` builds yet. Let's just allow two cases at the moment: 
* user provided platform
* mixlib-install auto-detected platform

**Comment by wrightp** [comment]
@schisamo one more time
