### PR TITLE
Fix permissions on automate keys and license.

### LINKED ISSUE #195: delivery.license as created by chef-ingredient
### Chef-client version
chef-client version: 12.21.2

### Platform Details
SLESsp2

### Scenario:
The owner and permissions of delivery.license as created by chef-ingredient do not match those as when the command "automate-ctl reconfigure" is run. This is causing the license to be unreadable and shows up as expired

### Steps to Reproduce:
chef-val-wfl.hplab1.ford.com cookbook_file[/opt/delivery/embedded/cookbooks/delivery/recipes/nginx.rb] action create[2017-08-07T09:43:56-04:00] INFO: Processing cookbook_file[/opt/delivery/embedded/cookbooks/delivery/recipes/nginx.rb] action create (ford_pipeline_build::chef_automate line 47)
chef-val-wfl.hplab1.ford.com (up to date)
chef-val-wfl.hplab1.ford.com chef_automate[chef-val-wfl.hplab1.ford.com] action create[2017-08-07T09:43:56-04:00] INFO: Processing chef_automate[chef-val-wfl.hplab1.ford.com] action create (ford_pipeline_build::chef_automate line 56)
chef-val-wfl.hplab1.ford.com
chef-val-wfl.hplab1.ford.com chef_ingredient[automate] action upgrade[2017-08-07T09:43:56-04:00] INFO: Processing chef_ingredient[automate] action upgrade (/var/chef/cache/cookbooks/chef-ingredient/resources/automate.rb line 51)
chef-val-wfl.hplab1.ford.com
chef-val-wfl.hplab1.ford.com ruby_block[stop chef run] action nothing[2017-08-07T09:43:56-04:00] INFO: Processing ruby_block[stop chef run] action nothing (/var/chef/cache/cookbooks/chef-ingredient/libraries/helpers.rb line 251)
chef-val-wfl.hplab1.ford.com (skipped due to action :nothing)
chef-val-wfl.hplab1.ford.com remote_file[/var/chef/cache/automate-1.5.46-1.el6.x86_64.rpm] action create[2017-08-07T09:43:56-04:00] INFO: Processing remote_file[/var/chef/cache/automate-1.5.46-1.el6.x86_64.rpm] action create (/var/chef/cache/cookbooks/chef-ingredient/libraries/default_handler.rb line 104)
chef-val-wfl.hplab1.ford.com (up to date)
chef-val-wfl.hplab1.ford.com zypper_package[automate] action upgrade[2017-08-07T09:43:58-04:00] INFO: Processing zypper_package[automate] action upgrade (/var/chef/cache/cookbooks/chef-ingredient/libraries/default_handler.rb line 55)
chef-val-wfl.hplab1.ford.com (up to date)
chef-val-wfl.hplab1.ford.com (up to date)
chef-val-wfl.hplab1.ford.com directory[/etc/delivery] action create[2017-08-07T09:43:58-04:00] INFO: Processing directory[/etc/delivery] action create (/var/chef/cache/cookbooks/chef-ingredient/resources/automate.rb line 62)
chef-val-wfl.hplab1.ford.com (up to date)
chef-val-wfl.hplab1.ford.com directory[/etc/chef] action create[2017-08-07T09:43:58-04:00] INFO: Processing directory[/etc/chef] action create (/var/chef/cache/cookbooks/chef-ingredient/resources/automate.rb line 62)
chef-val-wfl.hplab1.ford.com (up to date)
chef-val-wfl.hplab1.ford.com directory[/var/opt/delivery/license] action create[2017-08-07T09:43:58-04:00] INFO: Processing directory[/var/opt/delivery/license] action create (/var/chef/cache/cookbooks/chef-ingredient/resources/automate.rb line 62)
chef-val-wfl.hplab1.ford.com (up to date)
chef-val-wfl.hplab1.ford.com chef_file[/var/opt/delivery/license/delivery.license] action create[2017-08-07T09:43:58-04:00] INFO: Processing chef_file[/var/opt/delivery/license/delivery.license] action create (/var/chef/cache/cookbooks/chef-ingredient/resources/automate.rb line 73)
chef-val-wfl.hplab1.ford.com
chef-val-wfl.hplab1.ford.com * cookbook_file[/var/opt/delivery/license/delivery.license] action create[2017-08-07T09:43:58-04:00] INFO: Processing cookbook_file[/var/opt/delivery/license/delivery.license] action create (/var/chef/cache/cookbooks/chef-ingredient/resources/file.rb line 40)
chef-val-wfl.hplab1.ford.com [2017-08-07T09:43:58-04:00] INFO: cookbook_file[/var/opt/delivery/license/delivery.license] owner changed to 0
chef-val-wfl.hplab1.ford.com [2017-08-07T09:43:58-04:00] INFO: cookbook_file[/var/opt/delivery/license/delivery.license] mode changed to 600
chef-val-wfl.hplab1.ford.com
chef-val-wfl.hplab1.ford.com - change mode from '0644' to '0600'
chef-val-wfl.hplab1.ford.com - change owner from 'deliver5' to 'root'
chef-val-wfl.hplab1.ford.com

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

### PR DESCRIPTION
**Pull request by ncerny**
Signed-off-by: Nathan Cerny <ncerny@gmail.com>

### Description

[Describe what this change achieves]

### Issues Resolved

Fixes #195 

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

File: resources/automate.rb [hunk 1]
```diff
@@ -59,26 +59,41 @@
     platform_version new_resource.platform_version if new_resource.platform_version
   end
 
+  os_user = new_resource.config[/user\['username'\] ?= ?['"](?<username>.*)['"]/, 'username'] || 'delivery'
```
Comment (wrightp) [inline resources/automate.rb]: Could we please add a comment describing what these few lines are doing?

**Comment by wrightp** [comment]
@chef-cookbooks/chef-ingredient-maintainers
